name: auto merge

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  merge:
    name: auto merge all approved PRs
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DINGDING_ACCESS_TOKEN: ${{ secrets.DINGING_ACCESS_TOKEN }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
