name: test

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-flow:
    name: test
    runs-on: ubuntu-latest
    steps : 
    - name: Check out main branch
      uses: actions/checkout@v2
      with:
        ref: test
    - name: Intall Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: node test.js
      working-directory: src/