name: test

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-flow:
    name: test
    runs-on: ubuntu-latest
    steps : 
    - name: Check out main branch
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Intall Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        echo "OWNER_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      shell: bash
    - run: npm install
    - run: ls
    - run: cd Git_Action_Test
    - run: ls
    - run: cd src
    - run: node test.js
      env: 
        cmd: 'echo blabla'
      
